apiVersion: v1
kind: ReplicationController
metadata: 
  name: myrc
spec:
  replicas: 2
  selector:
     app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: con1
        image: nginx:latest
        ports:
        - containerPort: 80
