apiVersion: v1
kind: Pod
metadata:
  name: mypod
  labels:
    app: myapp
    env: dev
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:  # min resources 
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "256Mi"
        cpu: "500m"
  - name: con2
    image: tomcat:latest
    ports:
    - containerPort: 8080
